enableScripts: true

nodeLinker: node-modules

npmScopes:
  tinyaxis:
    npmRegistryServer: "https://registry.npmjs.org"
    npmAuthToken: "${TINYAXIS_NPM_TOKEN:-}"

yarnPath: .yarn/releases/yarn-4.17.1.cjs
